### ISSUE TITLE
Basic configuration returns error message

### ISSUE THREAD

**Issue by cjstone** [devopsdunkin/terraform-provider-nagios#58] opened 2019-12-11 16:09 UTC
I've pared down my .tf file to this:

```
provider "nagios" {
    url = "http://monitor.example.com/nagiosxi"
    token = "XXXXX"
}

resource "nagios_host" "install2" {
    name                            = "install2"
    address                         = "172.24.20.202"
    max_check_attempts              = "10"
    check_period                    = "24x7"
    notification_interval           = "1"
    notification_period             = "24x7"
    contacts                        = [
        "nagiosadmin"
    ]
}
```

When I apply, the host is added to nagios. However, the run also results in this error message:

```nagios_host.install2: Creating...

Error: json: cannot unmarshal object into Go value of type []nagios.Host

  on nagios.tf line 6, in resource "nagios_host" "install2":
   6: resource "nagios_host" "install2" {
 ```

I'm not able to see what in my config is causing this.

I'm running the latest MacOS executable and Terraform 12.

Thanks,

--Chris

**Comment by devopsdunkin** [comment] 2019-12-12 01:40
Hey Chris - Sorry to hear you're having trouble. I had a couple of follow up questions for you on this:

1. What minor release of Terraform 0.12.x are you running?
2. What version of Nagios XI?

Also, could you turn up logging and apply your TF config again?

```
export TF_LOG="DEBUG"
export TF_LOG_PATH="debug.log"
```

That will dump the logs in the same directory as your TF config. If you could attach that to the issue so I can take a peak. I have an idea of why this might be failing and I'm actively working on a new release in the coming few days that I hope will fix it, but the logs would help narrow that down.

Thanks,
Chris

**Comment by cjstone** [comment] 2019-12-12 16:01
Thanks Chris! I really appreciate your help with this...

Terraform: Terraform v0.12.17
Nagios XI: 5.5.7

Perhaps Nagios is too old? I can try upgrading later today.

Debug log:

[debug.log](https://github.com/devopsdunkin/terraform-provider-nagios/files/3956680/debug.log)

Thanks again,

--Chris

**Comment by devopsdunkin** [comment] 2019-12-13 03:55
Hey Chris - So I spun up an instance of Nagios 5.5.7 and was able to reproduce the issue, so it looks like it's that version that the provider doesn't like. I did most of the development on Nagios 5.6.1 and recently updated to 5.6.7, which is one of the more recent releases. I would definitely try an upgrade and see if that helps. Let me know how it goes!

Also, I've used the docker image for Nagios XI to do a lot of testing with the provider. It's been really great to use, if you want an easy lab environment for Nagios. I think the current version is at 5.6.1.

https://hub.docker.com/r/tgoetheyn/docker-nagiosxi/

Thanks,
Chris

**Comment by devopsdunkin** [comment] 2019-12-16 01:37
Hey Chris - How'd the upgrade go? Did that help with this at all?

**Comment by cjstone** [comment] 2019-12-16 16:01
Hi Chris, thanks for checking back. We're still waiting for Nagios to get upgraded -- there's been some issues doing that apparently. I'll keep you posted once we get that done and I can test the provider again. Thanks again! --Chris

**Comment by cjstone** [comment] 2019-12-17 18:28
Hi Chris, we upgraded and the issue went away. Thanks for your help!

--Chris

**Comment by devopsdunkin** [comment] 2019-12-18 02:06
Good to hear! I'll close this issue out, but if you have any other questions or issues, definitely reach out!

**Closed by devopsdunkin** 2019-12-18 02:06 UTC
